### PR TITLE
fix #47 add availability restriction

### LINKED ISSUE #47: Missing restrictions within the seactionheader
Compared to 3.11, the 4.4 version is missing the restrictions in the Section Header if set for a topic. 

**3.11**
twocol-3 11

**4.4**
twocol-4 4

### PR DESCRIPTION
**Pull request by gbarat87**
Adding the availability data. 
Display the data in the topic mustache

Screenshot from 2024-11-14 14-51-57

### CODE REVIEW

**Comment by meepster-nz** [comment]
Looks good.

**Comment by gbarat87** [comment]
switch `<div>` for `<li>` and moved the block in the `<ul>` part

**Comment by golenkovm** [comment]
Thanks @gbarat87 beofre we proceed could you please post a link to the similar code places of other course formats, eg for core ones? Just to check how it's managed there

**Comment by gbarat87** [comment]
Hi @golenkovm Here is an example for the course_format_tiles
Mustache => 
https://bitbucket.org/dw8/moodle-format_tiles/src/a403d6966e449a765177e8caca5e118f925bc9b9/templates/local/content/section/content.mustache#lines-104:115

Backend => 
https://bitbucket.org/dw8/moodle-format_tiles/src/a403d6966e449a765177e8caca5e118f925bc9b9/classes/output/course_output.php#lines-656

**Comment by golenkovm** [comment]
Ok, cool. Thanks @gbarat87

**Pull request merged**
